language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm test
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: chatty-1718
  skip_cleanup: true
  local_dir: dist
  notifications:
  email:
    on_failure: always
